--- CLEANING
DROP TABLE PRODUCENCI cascade constraints;
DROP TABLE PRODUKTY cascade constraints;
DROP TABLE KLIENCI cascade constraints;
DROP TABLE ZAMOWIENIA cascade constraints;
DROP TABLE DOSTAWY cascade constraints;
DROP TABLE BUDYNKI cascade constraints;
DROP TABLE STANOWISKA cascade constraints;
DROP TABLE PRACOWNICY cascade constraints;
DROP TABLE DANEKONTAKTOWE cascade constraints;


--- TABELA BUDYNKI ---
CREATE TABLE BUDYNKI
(
    idBudynku NUMBER(3) PRIMARY KEY,
	nazwa_budynku VARCHAR(15),
	idDaneKontaktowe NUMBER(3) NOT NULL UNIQUE,
    idKierownika NUMBER(3) NOT NULL
);
--- TABELA PRACOWNICY
CREATE TABLE PRACOWNICY
(
	idPracownika NUMBER(3) PRIMARY KEY,
	nazwisko_Pracownika VARCHAR(15) NOT NULL,
	haslo VARCHAR(32) NOT NULL,
	idStanowiska NUMBER(3),
	idBudynku NUMBER(3),
	idDaneKontaktowe NUMBER(3) UNIQUE
);
--- TABELA STANOWISKA
CREATE TABLE STANOWISKA
(
	idStanowiska NUMBER(3) PRIMARY KEY,
	pensja INTEGER NOT NULL,
	nazwaStanowiska VARCHAR2(20) UNIQUE
);
-- TABLEA DANE KONTAKTOWE
CREATE TABLE DANEKONTAKTOWE
(
	idDaneKontaktowe Number(3) PRIMARY KEY,
	kodPocztowy NUMBER(5) NOT NULL,
	miast VARCHAR2(30) NOT NULL,
	ulica VARCHAR2(15) NOT NULL,
	numerBudynku INTEGER,
	numerTelefonu VARCHAR2(15)

);
--- TABELA DOSTAWY
CREATE TABLE DOSTAWY
(
	idDostawy NUMBER(3) PRIMARY KEY,
	data_dostawy DATE,
	ilosc INTEGER,
	idProduktu NUMBER(3),
	idKierownika NUMBER(3)
);
--- TABELA KLIENCI
CREATE TABLE KLIENCI
(
	idKlienta NUMBER(3) PRIMARY KEY,
	nazwiskoKlienta VARCHAR2(15), 
	idDaneKontaktowe NUMBER(3) UNIQUE
);
-- TABELA ZAMOWIENIA
CREATE TABLE ZAMOWIENIA
(
	idZamowienia NUMBER(3) PRIMARY KEY,
	ilosc INTEGER NOT NULL,
	data_Zamowienia Date NOT NULL,
	idKlienta NUMBER(3),
	idProduktu NUMBER(3),
	idPracownika NUMBER(3)
	
);

CREATE TABLE PRODUKTY
(
	idProduktu NUMBER(3) PRIMARY KEY,
	nazwa_produktu VARCHAR2(32) NOT NULL UNIQUE,
	cena FLOAT NOT NULL,
	idBudynku NUMBER(3),
	idProducenta NUMBER(3)
);
CREATE TABLE PRODUCENCI
(
	idProducenta NUMBER(3) PRIMARY KEY,
	nazwa_Producenta VARCHAR2(30) NOT NULL,
	idDaneKontaktowe NUMBER(3) UNIQUE
);
---- CONSTRAINTS BUDYNKI
ALTER TABLE BUDYNKI ADD FOREIGN KEY (idDaneKontaktowe) REFERENCES DANEKONTAKTOWE(idDaneKontaktowe);
ALTER TABLE BUDYNKI ADD FOREIGN KEY (idKierownika) REFERENCES PRACOWNICY(idPracownika);

--- CONSTRAINTS PRACOWNICY
ALTER TABLE PRACOWNICY ADD FOREIGN KEY (idStanowiska) REFERENCES STANOWISKA(idStanowiska);
ALTER TABLE PRACOWNICY ADD FOREIGN KEY (idBudynku) REFERENCES BUDYNKI(idBudynku);
ALTER TABLE PRACOWNICY ADD FOREIGN KEY (idDaneKontaktowe) REFERENCES DANEKONTAKTOWE(idDaneKontaktowe);

--- CONSTRAINTS DOSTAWY
ALTER TABLE DOSTAWY ADD FOREIGN KEY (idDostawy) REFERENCES PRACOWNICY(idPracownika);
ALTER TABLE DOSTAWY ADD FOREIGN KEY (idProduktu) REFERENCES PRODUKTY(idProduktu);
--- CONSTRAINTS PRODUCENCI
ALTER TABLE PRODUCENCI ADD FOREIGN KEY (idDaneKontaktowe) REFERENCES DANEKONTAKTOWE(idDaneKontaktowe);

--- CONSTRAINTS KLIENCI
ALTER TABLE KLIENCI ADD FOREIGN KEY (idDaneKontaktowe) REFERENCES DANEKONTAKTOWE(idDaneKontaktowe);

---CONSTRAINTS ZAMOWIENIA
ALTER TABLE ZAMOWIENIA ADD FOREIGN KEY (idKlienta) REFERENCES KLIENCI(idKlienta);
ALTER TABLE ZAMOWIENIA ADD FOREIGN KEY (idProduktu) REFERENCES PRODUKTY(idProduktu);
ALTER TABLE ZAMOWIENIA ADD FOREIGN KEY (idPracownika) REFERENCES PRACOWNICY(idPracownika);

---CONSTRAINTS PRODUKTY
ALTER TABLE PRODUKTY ADD FOREIGN KEY (idBudynku) REFERENCES BUDYNKI(idBudynku);
ALTER TABLE PRODUKTY ADD FOREIGN KEY (idProducenta) REFERENCES PRODUCENCI(idProducenta);

